version: 2
jobs:
  build:
    working_directory: ~/pillar-bcx-pubsub
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: |
            curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ./.npmrc
            echo "registry=https://pillarproject.jfrog.io/pillarproject/api/npm/npm/" >> ./.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependenciues
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
#      - run:
#          name: eslint
#          command: npm run lint
      - run:
          name: unit-test
          command: npm run test:coverage
#      - run:
#          name: plato
#          command:  npm run plato
      - store_artifacts:
          path: ./reports/
          destination: reports

  whitesource:
    working_directory: ~/pillar-bcx-pubsub
    docker:
      - image: circleci/openjdk:8-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/pillar-bcx-pubsub/workspace
      - run :
          name: Setup WhiteSource
          command: curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh
      - run:
          name: execute whitesource
          command: |
            cd .whitesource/
            chmod +x wss_agent.sh && ./wss_agent.sh -apiKey $WHITESOURCE_API_KEY -c ./whitesource-fs-agent.config  -project pillar-bcx-pubsub -f files.list

  publish:
    working_directory: ~/pillar-bcx-pubsub
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
          name: Authenticate with registry
          command: |
            curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillar-bcx-pubsub/.npmrc
            echo "registry=https://pillarproject.jfrog.io/pillarproject/api/npm/npm/" >> ./.npmrc
      - run:
          name: Publish Package to Artifactory
          command: |
            npm publish --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
            chmod +x .circleci/announceRelease.sh && .circleci/announceRelease.sh "BCX-PUBSUB" "$(node -e "console.log(require('./package.json').name)"):$(node -e "console.log($CIRCLE_BUILD_NUM)")"

workflows:
  version: 2
  test_and_publish:
    jobs:
      - build
      - whitesource:
          requires:
             - build
      - publish:
          requires:
             - build
          filters:
            branches:
              only:
                  - master
